import { IEditorFormlyField } from '@src/app/shared/models/widget.model';

export const widget_select_config: IEditorFormlyField[] = [
  {
    type: 'tabs',
    props: {
      label: '页签',
      icon: 'tab',
      placeholder: '',
      disabled: false,
      density: 1,
    },
    className: 'hs-density--1 mat-tab-item3-full',
    fieldGroup: [
      {
        type: 'column',
        props: {
          label: '外观',
          placeholder: '',
          disabled: false,
          density: 1,
        },
        className: 'hs-density--1',
        fieldGroup: [
          {
            key: 'props.label',
            type: 'input',
            props: {
              type: 'text',
              label: '标题',
              placeholder: '',
              disabled: false,
              appearance: 'outline',
              density: 5,
              description: '',
              required: false,
              readonly: false,
            },
            className: 'hs-density--5',
          },
          {
            key: 'props.density',
            type: 'number',
            props: {
              label: '密度',
              appearance: 'outline',
              min: 0,
              max: 5,
            },
            className: 'hs-density--5',
          },
          {
            key: 'props.appearance',
            type: 'radio',
            props: {
              appearance: 'outline',
              label: '样式类型',
              options: [
                { value: 'fill', label: '填满' },
                { value: 'outline', label: '线条' },
              ],
            },
            className: 'hs-density--5',
          },
          {
            key: 'props.placeholder',
            type: 'input',
            props: {
              type: 'text',
              label: '提示',
              placeholder: '',
              disabled: false,
              appearance: 'outline',
              density: 5,
              description: '',
              required: false,
              readonly: false,
            },
            className: 'hs-density--5',
          },
        ],
      },
      {
        type: 'column',
        props: {
          label: '数据',
          placeholder: '',
          disabled: false,
          density: 1,
        },
        className: 'hs-density--1',
        fieldGroup: [
          {
            key: 'fieldId',
            type: 'input',
            props: {
              type: 'text',
              label: '组件ID',
              placeholder: '',
              disabled: true,
              appearance: 'outline',
              density: 5,
              description: '',
              required: false,
              readonly: false,
            },
            className: 'hs-density--5',
          },
          {
            key: 'key',
            type: 'input',
            props: {
              type: 'text',
              label: '组件绑定数据key',
              placeholder: '',
              disabled: false,
              appearance: 'outline',
              density: 5,
              description: '',
              required: false,
              readonly: false,
            },
            className: 'hs-density--5',
          },
          {
            key: 'props.options',
            type: 'run-subtable',
            props: {
              typeName: '普通输入子表',
              placeholder: '',
              disabled: false,
              styles: {
                borderWidth: 0,
                borderRadius: 0,
                borderColor: 'transparent',
              },
            },
            fieldId: 'subtable_key_6566596701791895',
            id: 'formly_25_subtable_6566596701791895_2',
            hooks: {},
            modelOptions: {},
            validation: {
              messages: {},
            },
            expressions: {},
            expressionProperties: {},
            className: 'hs-density--undefined ',
            fieldArray: {
              fieldGroup: [
                {
                  key: 'label',
                  type: 'input',
                  defaultValue: '选项x',
                  props: {
                    type: 'text',
                    label: '标签',
                    typeName: '单行文本',
                    placeholder: '',
                    disabled: false,
                    appearance: 'outline',
                    density: 5,
                    description: '',
                    required: false,
                    readonly: false,
                    row: 1,
                  },
                  isPlaceholder: true,
                  fieldId: 'input_key_3087500571260556',
                  id: 'formly_90_input_3087500571260556_0',
                  hooks: {},
                  modelOptions: {},
                  validation: {
                    messages: {},
                  },
                  expressions: {},
                  expressionProperties: {},
                  className: 'hs-density--5 ',
                },
                {
                  key: 'value',
                  type: 'input',
                  defaultValue: 'x',
                  props: {
                    type: 'text',
                    label: '值',
                    typeName: '单行文本',
                    row: 1,
                    placeholder: '',
                    disabled: false,
                    appearance: 'outline',
                    density: 5,
                    description: '',
                    required: false,
                    readonly: false,
                  },
                  isPlaceholder: true,
                  fieldId: 'input_key_5707678850497686',
                  id: 'formly_112_input_5707678850497686_1',
                  hooks: {},
                  modelOptions: {},
                  validation: {
                    messages: {},
                  },
                  expressions: {},
                  expressionProperties: {},
                  className: 'hs-density--5 ',
                  focus: false,
                },
              ],
            },
          },
        ],
      },
      {
        key: '949865101136',
        type: 'column',
        props: {
          label: '交互',
          placeholder: '',
          disabled: false,
          density: 1,
        },
        className: 'hs-density--1',
        fieldGroup: [
          {
            key: '356800710424',
            type: 'input',
            props: {
              label: '第三个文本',
              placeholder: '',
              disabled: false,
              appearance: 'outline',
              density: 5,
              description: '',
              required: false,
              readonly: false,
              type: 'password',
            },
            className: 'hs-density--5',
          },
          {
            key: '798540614610',
            type: 'checkbox',
            props: {
              label: '多选',
              placeholder: '',
              disabled: false,
              appearance: 'outline',
              density: 5,
              description: '',
              required: false,
              readonly: false,
              options: [
                {
                  value: 1,
                  label: '选项 1',
                },
                {
                  value: 2,
                  label: '选项 2',
                },
                {
                  value: 3,
                  label: '选项 3',
                },
                {
                  value: 4,
                  label: '选项 4',
                  disabled: true,
                },
              ],
              hideFieldUnderline: true,
              indeterminate: true,
              floatLabel: 'always',
              hideLabel: true,
              color: 'accent',
            },
            className: 'hs-density--5',
          },
        ],
      },
    ],
  },
];
