import { IEditorFormlyField } from '@src/app/shared/models/widget.model';

export const dashboard_widget_config: IEditorFormlyField[] = [
  {
    key: 'anableFullscreen',
    type: 'switch',
    templateOptions: {
      label: '启用全屏',
      hideLabel: true,
      layout: 'left',
      labelWidth: '100px',
    },
  },
  {
    template: '<div class="py-12px">标题</div>',
  },
  {
    key: 'showTitle',
    type: 'switch',
    templateOptions: {
      label: '显示标题',
      hideLabel: true,
      layout: 'left',
      labelWidth: '100px',
    },
  },
  {
    key: 'title',
    type: 'input',
    props: {
      type: 'text',
      label: '单行文本',
      layout: 'left',
      hideLabel: true,
      labelWidth: '100px',
    },
    className: 'hs-density--5',
  },
  {
    key: 'titleTooltiptitle',
    type: 'input',
    props: {
      type: 'text',
      label: '标题提示文字',
      layout: 'left',
      hideLabel: true,
      labelWidth: '100px',
    },
    className: 'hs-density--5',
  },
  {
    template: '<div class="py-12px">标题图标</div>',
  },
  {
    key: 'showTitleIcon',
    type: 'switch',
    templateOptions: {
      label: '显示标题图标',
      hideLabel: true,
      layout: 'left',
      labelWidth: '100px',
    },
  },
  {
    key: 'icon',
    type: 'input',
    templateOptions: {
      label: '标题图标',
      hideLabel: true,
      layout: 'left',
      labelWidth: '100px',
    },
  },
  {
    template: '<div class="py-12px">容器样式</div>',
  },
  {
    key: 'backgroundColor',
    type: 'color-picker',
    props: {
      type: 'text',
      label: '背景颜色',
      layout: 'left',
      hideLabel: true,
      labelWidth: '100px',
    },
    className: 'hs-density--5',
  },
  {
    key: 'backgroundColor',
    type: 'color-picker',
    props: {
      type: 'text',
      label: '文字颜色',
      layout: 'left',
      hideLabel: true,
      labelWidth: '100px',
    },
    className: 'hs-density--5',
  },
  {
    template: '<div class="py-4px text-14px">内边距</div>',
  },
  {
    type: 'grid',
    fieldGroup: [
      {
        key: 'paddingTop',
        type: 'input',
        props: {
          type: 'number',
          label: '上',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },

      {
        key: 'paddingRight',
        type: 'input',
        props: {
          type: 'number',
          label: '右',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
      {
        key: 'paddingBottom',
        type: 'input',
        props: {
          type: 'number',
          label: '下',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
      {
        key: 'paddingLeft',
        type: 'input',
        props: {
          type: 'number',
          label: '左',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
    ],
  },
  {
    template: '<div class="py-4px text-14px">外边距</div>',
  },
  {
    type: 'grid',
    fieldGroup: [
      {
        key: 'marginTop',
        type: 'input',
        props: {
          type: 'number',
          label: '上',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },

      {
        key: 'marginRight',
        type: 'input',
        props: {
          type: 'number',
          label: '右',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
      {
        key: 'paddinBottom',
        type: 'input',
        props: {
          type: 'number',
          label: '下',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
      {
        key: 'marginLeft',
        type: 'input',
        props: {
          type: 'number',
          label: '左',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
    ],
  },
  {
    template: '<div class="py-4px text-14px">圆角</div>',
  },
  {
    type: 'grid',
    fieldGroup: [
      {
        key: 'borderTopLeftRadius',
        type: 'input',
        props: {
          type: 'number',
          label: '左上',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },

      {
        key: 'borderTopRightRadius',
        type: 'input',
        props: {
          type: 'number',
          label: '右上',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
      {
        key: 'borderBottomRightRadius',
        type: 'input',
        props: {
          type: 'number',
          label: '右下',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
      {
        key: 'borderBottomLeftRadius',
        type: 'input',
        props: {
          type: 'number',
          label: '左下',
          row: 1,
          appearance: 'outline',
          density: 5,
          layout: 'float',
          hideLabel: false,
          units: 'px',
          floatLabel: 'always',
        },
      },
    ],
  },
];
