import { IUserRequiredAction } from '@src/app/shared/models/user.model';

export const userRequiredCtions: Array<IUserRequiredAction> = [
  {
    alias: 'CONFIGURE_TOTP',
    name: 'Configure OTP',
    providerId: 'CONFIGURE_TOTP',
    enabled: true,
    defaultAction: false,
    priority: 10,
    config: {},
    label: '配置一次性密码',
  },
  {
    alias: 'TERMS_AND_CONDITIONS',
    name: 'Terms and Conditions',
    providerId: 'TERMS_AND_CONDITIONS',
    enabled: false,
    defaultAction: false,
    priority: 20,
    config: {},
    label: '条款与条件',
  },
  {
    alias: 'UPDATE_PASSWORD',
    name: 'Update Password',
    providerId: 'UPDATE_PASSWORD',
    enabled: true,
    defaultAction: false,
    priority: 30,
    config: {},
    label: '更新密码',
  },
  {
    alias: 'UPDATE_PROFILE',
    name: 'Update Profile',
    providerId: 'UPDATE_PROFILE',
    enabled: true,
    defaultAction: false,
    priority: 40,
    config: {},
    label: '更新个人资料',
  },
  {
    alias: 'VERIFY_EMAIL',
    name: 'Verify Email',
    providerId: 'VERIFY_EMAIL',
    enabled: true,
    defaultAction: false,
    priority: 50,
    config: {},
    label: '验证电子邮件',
  },
  {
    alias: 'delete_account',
    name: 'Delete Account',
    providerId: 'delete_account',
    enabled: false,
    defaultAction: false,
    priority: 60,
    config: {},
    label: '删除账户',
  },
  {
    alias: 'webauthn-register',
    name: 'Webauthn Register',
    providerId: 'webauthn-register',
    enabled: true,
    defaultAction: false,
    priority: 70,
    config: {},
    label: 'WebAuthn 注册',
  },
  {
    alias: 'webauthn-register-passwordless',
    name: 'Webauthn Register Passwordless',
    providerId: 'webauthn-register-passwordless',
    enabled: true,
    defaultAction: false,
    priority: 80,
    config: {},
    label: 'WebAuthn 无密码注册',
  },
  {
    alias: 'delete_credential',
    name: 'Delete Credential',
    providerId: 'delete_credential',
    enabled: true,
    defaultAction: false,
    priority: 100,
    config: {},
    label: '删除凭据',
  },
  {
    alias: 'update_user_locale',
    name: 'Update User Locale',
    providerId: 'update_user_locale',
    enabled: true,
    defaultAction: false,
    priority: 1000,
    config: {},
    label: '更新用户地区设置',
  },
];
