import { Injectable, signal } from '@angular/core';
import { MenuHttpService } from '@src/app/core/http/menu.service';
import { IMenuNode } from '@src/app/shared/models/app-menu.model';

@Injectable({ providedIn: 'root' })
export class MenuManagementService {
  // 全局菜单配置数据
  globalMenuConfig = signal<any>({
    themeId: '2',
    parent: {
      default: {
        fontSizeUnits: 'px',
        borderTopWidthUnits: 'px',
        borderRightWidthUnits: 'px',
        borderBottomWidthUnits: 'px',
        borderLeftWidthUnits: 'px',
        paddingTopUnits: 'px',
        paddingRightUnits: 'px',
        paddingBottomUnits: 'px',
        paddingLeftUnits: 'px',
        borderTopLeftRadiusUnits: 'px',
        borderTopRightRadiusUnits: 'px',
        borderBottomRightRadiusUnits: 'px',
        borderBottomLeftRadiusUnits: 'px',
        heightUnits: 'px',
        fontSize: 14,
        height: 38,
        color: 'rgb(255,255,255)',
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
        borderBottomRightRadius: 8,
        borderBottomLeftRadius: 8,
      },
      hover: {
        fontSizeUnits: 'px',
        borderTopWidthUnits: 'px',
        borderRightWidthUnits: 'px',
        borderBottomWidthUnits: 'px',
        borderLeftWidthUnits: 'px',
        paddingTopUnits: 'px',
        paddingRightUnits: 'px',
        paddingBottomUnits: 'px',
        paddingLeftUnits: 'px',
        borderTopLeftRadiusUnits: 'px',
        borderTopRightRadiusUnits: 'px',
        borderBottomRightRadiusUnits: 'px',
        borderBottomLeftRadiusUnits: 'px',
        heightUnits: 'px',
        backgroundColor: '#3a4560',
        height: 38,
      },
      active: {
        fontSizeUnits: 'px',
        borderTopWidthUnits: 'px',
        borderRightWidthUnits: 'px',
        borderBottomWidthUnits: 'px',
        borderLeftWidthUnits: 'px',
        paddingTopUnits: 'px',
        paddingRightUnits: 'px',
        paddingBottomUnits: 'px',
        paddingLeftUnits: 'px',
        borderTopLeftRadiusUnits: 'px',
        borderTopRightRadiusUnits: 'px',
        borderBottomRightRadiusUnits: 'px',
        borderBottomLeftRadiusUnits: 'px',
        heightUnits: 'px',
        backgroundColor: '#3a4560',
        height: 38,
      },
    },
    children: {
      default: {
        fontSizeUnits: 'px',
        borderTopWidthUnits: 'px',
        borderRightWidthUnits: 'px',
        borderBottomWidthUnits: 'px',
        borderLeftWidthUnits: 'px',
        paddingTopUnits: 'px',
        paddingRightUnits: 'px',
        paddingBottomUnits: 'px',
        paddingLeftUnits: 'px',
        borderTopLeftRadiusUnits: 'px',
        borderTopRightRadiusUnits: 'px',
        borderBottomRightRadiusUnits: 'px',
        borderBottomLeftRadiusUnits: 'px',
        heightUnits: 'px',
        fontSize: 14,
        height: 38,
        color: 'rgb(255,255,255)',
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
        borderBottomRightRadius: 8,
        borderBottomLeftRadius: 8,
      },
      hover: {
        fontSizeUnits: 'px',
        borderTopWidthUnits: 'px',
        borderRightWidthUnits: 'px',
        borderBottomWidthUnits: 'px',
        borderLeftWidthUnits: 'px',
        paddingTopUnits: 'px',
        paddingRightUnits: 'px',
        paddingBottomUnits: 'px',
        paddingLeftUnits: 'px',
        borderTopLeftRadiusUnits: 'px',
        borderTopRightRadiusUnits: 'px',
        borderBottomRightRadiusUnits: 'px',
        borderBottomLeftRadiusUnits: 'px',
        heightUnits: 'px',
        backgroundColor: '#3a4560',
        height: 38,
      },
      active: {
        fontSizeUnits: 'px',
        borderTopWidthUnits: 'px',
        borderRightWidthUnits: 'px',
        borderBottomWidthUnits: 'px',
        borderLeftWidthUnits: 'px',
        paddingTopUnits: 'px',
        paddingRightUnits: 'px',
        paddingBottomUnits: 'px',
        paddingLeftUnits: 'px',
        borderTopLeftRadiusUnits: 'px',
        borderTopRightRadiusUnits: 'px',
        borderBottomRightRadiusUnits: 'px',
        borderBottomLeftRadiusUnits: 'px',
        heightUnits: 'px',
        backgroundColor: '#3a4560',
        height: 38,
      },
    },
    menuContainer: {
      backgroundColor: 'rgb(44,53,76)',
      width: 225,
      paddingTopUnits: 'px',
      paddingRightUnits: 'px',
      paddingBottomUnits: 'px',
      paddingLeftUnits: 'px',
      widthUnits: 'px',
      paddingTop: 8,
      paddingRight: 8,
      paddingBottom: 8,
      paddingLeft: 8,
      levelPadding: 20,
    },
    showType: 'menuContainer',
  });

  // 菜单数据
  menuData = signal<IMenuNode[]>([]);

  // 仪表板数据
  dashboardData = signal<any>([]);

  constructor(private menuHttpService: MenuHttpService) {}
}
